fix: Minor changes in spec file (#11826)
**Signed-off-by:** Jagjeevan Kashid <jagjeevandev97@gmail.com>  
### What
Minor changes made in spec file as doc generation breaks due we are not
correctly escaping the usage of /, {, }, ?, etc. this cause errors at
compile time

<!-- IMPORTANT CHECKLIST
Make sure you've done all the following (You can delete the checklist
before submitting)
- [ ] PR title is prefixed by one of the following: feat, fix, docs,
style, refactor, test, build, ci, chore, revert, l10n, taxonomy
- [ ] Code is well documented
- [ ] Include unit tests for new functionality
- [ ] Code passes GitHub workflow checks in your branch
- [ ] If you have multiple commits please combine them into one commit
by squashing them.
- [ ] Read and understood the [contribution
guidelines](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/CONTRIBUTING.md)
-->


<!-- Describe the changes made and why they were made instead of how
they were made. -->

### Error Ex.
```yml
openapi git:(main) ✗ npm run build

> example-openapi@0.0.0 build
> next build

   ▲ Next.js 15.3.1

   Creating an optimized production build ...
[MDX] updated map file in 9ms
 ✓ Compiled successfully in 2000ms
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
 ⚠ metadataBase property in metadata export is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
Error occurred prerendering page "/docs/v2/read--requests/get-attribute-groups". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: lc is not defined
    at e6 (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/.next/server/chunks/846.js:1:37176)
    at e7 (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/.next/server/chunks/846.js:1:37479)
    at ek (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:17:13337)
    at e (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:17:17246)
    at e$ (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:17:17708)
    at Object.toJSON (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:17:14854)
    at stringify (<anonymous>)
    at eF (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:17:26079)
    at eq (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:17:26391)
    at ez (/Users/jagjeevankashid/Developer/doc/demo/fumadocs/openapi/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:17:26887)
Export encountered an error on /docs/[[...slug]]/page: /docs/v2/read--requests/get-attribute-groups, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
➜  openapi git:(main) ✗ 
```

---------

Signed-off-by: Jagjeevan <83103469+JagjeevanAK@users.noreply.github.com>