build(deps): bump @yaireo/tagify from 4.27.0 to 4.32.1 (#11051)
[//]: # (dependabot-start)
⚠️  **Dependabot is rebasing this PR** ⚠️ 

Rebasing might not happen immediately, so don't worry if this takes some
time.

Note: if you make any changes to this PR yourself, they will take
precedence over the rebase.

---

[//]: # (dependabot-end)

Bumps [@yaireo/tagify](https://github.com/yairEO/tagify) from 4.27.0 to
4.32.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/yairEO/tagify/releases"><code>@​yaireo/tagify</code>'s
releases</a>.</em></p>
<blockquote>
<h2>v4.32.1</h2>
<ul>
<li><a
href="https://redirect.github.com/yairEO/tagify/issues/1409">#1409</a> -
fixed incorrect example code bc63229</li>
<li>in normal mode, if there is a single tag and while the dropdown is
open the tag&amp;<a
href="https://redirect.github.com/yairEO/tagify/issues/39">#39</a>;s
<code>x</code> button is clicked, then the component should be
re-focused 9743bab</li>
<li>improved README <code>dropdown.includeSelectedTags</code> setting
description b39985c</li>
<li>removed <code>e.preventDefault</code> for <code>tab</code> keydown
event a321d15</li>
<li>typo fix  05e86a4</li>
</ul>
<p><a
href="https://github.com/yairEO/tagify/compare/v4.32.0...v4.32.1">https://github.com/yairEO/tagify/compare/v4.32.0...v4.32.1</a></p>
<h2>v4.32.0</h2>
<ul>
<li>should set the <code>selectOption</code> on the global state every
time <code>suggestionClick</code> is called (before it is called), which
can be either by mouse click or key press 34e81db</li>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1402">#1402</a> -
added <code>blur</code> event when a tag has focus (is editable) and
then blured. apparently the <code>onFocusBlur</code> does not catch this
blur event for some reason. 3e90111</li>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1400">#1400</a> -
tyrping text in the input element and pressing backspace key should not
rmove everything that was typed f0747d1</li>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1401">#1401</a> -
editing a tag and then selecting a suggestion (from the dropdown)
results in an error 0e0e851</li>
<li>fixes #<a
href="https://redirect.github.com/yairEO/tagify/issues/1403">#1403</a> -
added missing <code>async</code> keywrod for a function
<code>initReac</code> which uses <code>async</code> internally
f1bbd0c</li>
</ul>
<p><a
href="https://github.com/yairEO/tagify/compare/v4.31.6...v4.32.0">https://github.com/yairEO/tagify/compare/v4.31.6...v4.32.0</a></p>
<h2>v4.31.6</h2>
<ul>
<li>hopefully fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1378">#1378</a> -
Vue file with compilation error 9b2f3a9</li>
<li>should tab-autocomplete a tag from the whitelist and with all its
data, instead of only the suggetion&amp;<a
href="https://redirect.github.com/yairEO/tagify/issues/39">#39</a>;s
text, which is incorrect in case of a whitelist collection ab72938</li>
</ul>
<p><a
href="https://github.com/yairEO/tagify/compare/v4.31.5...v4.31.6">https://github.com/yairEO/tagify/compare/v4.31.5...v4.31.6</a></p>
<h2>v4.31.5</h2>
<ul>
<li>Calling <code>removeChild</code> in the <code>destory</code> method
only if <code>this.DOM.scope.parentNode</code> exists afade9e</li>
<li>Upgraded some packages  12f90dd</li>
<li>Fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1393">#1393</a> -
calling
<code>this.getPersistedData(&amp;[#39](https://github.com/yairEO/tagify/issues/39);value&amp;[#39](https://github.com/yairEO/tagify/issues/39);)</code>
should return nothing if <code>settings.id</code> is undefined
1d3419f</li>
<li>Fix error when DOM element is already detached during call to
destroy method a10ff9a</li>
<li>Bump rollup from 2.79.1 to 2.79.2  a5ff0d2</li>
</ul>
<p><a
href="https://github.com/yairEO/tagify/compare/v4.31.4...v4.31.5">https://github.com/yairEO/tagify/compare/v4.31.4...v4.31.5</a></p>
<h2>v4.31.4</h2>
<ul>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1374">#1374</a> -
add some protection in case <code>id</code> &amp;<a
href="https://redirect.github.com/yairEO/tagify/issues/39">#39</a>; does
not exists or if even <code>localStorage</code> does not exists
92dfd05</li>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1373">#1373</a> -
removed top-level <code>await</code> in order to resolve the error:
&quot;await is only valid in async functions and the top level bodies of
modules&quot; b0b16d3</li>
<li>added missing template mentioning in the README: <code>input</code>
template 0b2a55a</li>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1386">#1386</a> -
re-enabled <code>spellcheck</code> for the input component a459362</li>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1391">#1391</a> -
Can&amp;<a
href="https://redirect.github.com/yairEO/tagify/issues/39">#39</a>;t add
a tag with the value 0 as integer 5de627b</li>
<li>Fix test on settings &quot;dropdown.enable&quot; (should be
&quot;dropdown.enabled&quot; instead) f93da3e</li>
</ul>
<p><a
href="https://github.com/yairEO/tagify/compare/v4.31.3...v4.31.4">https://github.com/yairEO/tagify/compare/v4.31.3...v4.31.4</a></p>
<h2>v4.31.3</h2>
<ul>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1372">#1372</a> -
<code>this.value</code> was updated twice needlessly. It should only be
updated within the <code>postProcessNewTagNode</code> method
7cce53d</li>
</ul>
<p><a
href="https://github.com/yairEO/tagify/compare/v4.31.2...v4.31.3">https://github.com/yairEO/tagify/compare/v4.31.2...v4.31.3</a></p>
<h2>v4.31.2</h2>
<ul>
<li>fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1371">#1371</a> -
<code>add</code> event should fire ASAP without any delay. Also should
include invalid added tags f7c7a84</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/yairEO/tagify/commit/c719e25435e0d2e7a14622b05a3771bff5da5d1e"><code>c719e25</code></a>
4.32.1</li>
<li><a
href="https://github.com/yairEO/tagify/commit/bc63229ff68d3a01f165f3f467bb7b48f2517e20"><code>bc63229</code></a>
<a
href="https://redirect.github.com/yairEO/tagify/issues/1409">#1409</a> -
fixed incorrect example code</li>
<li><a
href="https://github.com/yairEO/tagify/commit/9743bab68e24b111adab767346fafc37e85f044d"><code>9743bab</code></a>
in normal mode, if there is a single tag and while the dropdown is open
the t...</li>
<li><a
href="https://github.com/yairEO/tagify/commit/b39985c9e141648bcc25e442b1bac08095c3283a"><code>b39985c</code></a>
improved README <code>dropdown.includeSelectedTags</code> setting
description</li>
<li><a
href="https://github.com/yairEO/tagify/commit/a321d15a19c42b8e84ad10d0f2f8d8e9dd34380c"><code>a321d15</code></a>
removed <code>e.preventDefault</code> for <code>tab</code> keydown
event</li>
<li><a
href="https://github.com/yairEO/tagify/commit/05e86a48dbe25b689079ad6c07e5bcb331f68d7f"><code>05e86a4</code></a>
typo fix</li>
<li><a
href="https://github.com/yairEO/tagify/commit/6a4cce73afb3afad990b5ccea52438edd13e6737"><code>6a4cce7</code></a>
4.32.0</li>
<li><a
href="https://github.com/yairEO/tagify/commit/34e81dbec1ebdf92f67d3539a7a98d182f2efcb0"><code>34e81db</code></a>
should set the <code>selectOption</code> on the global state every time
`suggestionClick...</li>
<li><a
href="https://github.com/yairEO/tagify/commit/3e90111b6956680dadac57cd57d588e17303ff36"><code>3e90111</code></a>
fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1402">#1402</a> -
added <code>blur</code> event when a tag has focus (is editable) and
then ...</li>
<li><a
href="https://github.com/yairEO/tagify/commit/f0747d18f5698b34c7c436b2b448a69667e44180"><code>f0747d1</code></a>
fixes <a
href="https://redirect.github.com/yairEO/tagify/issues/1400">#1400</a> -
tyrping text in the input element and pressing backspace key sh...</li>
<li>Additional commits viewable in <a
href="https://github.com/yairEO/tagify/compare/v4.27.0...v4.32.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=@yaireo/tagify&package-manager=npm_and_yarn&previous-version=4.27.0&new-version=4.32.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>